# Importing Datasets

In [1]:
import pandas as pd
import requests

## FARA - Food Access Research Atlas
We are interested in the <code>LILATracts_1And10</code> and <code>HUNVFlag</code> variables.

In [2]:
FARA = pd.read_csv('./2019 Food Access Research Atlas Data/Food Access Research Atlas.csv')

In [3]:
FARA.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [4]:
FARA_FD = FARA[['CensusTract', 'State', 'County', 'Urban', 'LILATracts_1And10', 'HUNVFlag']].copy()
FARA_FD.head()

   CensusTract    State          County  Urban  LILATracts_1And10  HUNVFlag
0   1001020100  Alabama  Autauga County      1                  0         0
1   1001020200  Alabama  Autauga County      1                  1         0
2   1001020300  Alabama  Autauga County      1                  0         0
3   1001020400  Alabama  Autauga County      1                  0         0
4   1001020500  Alabama  Autauga County      1                  0         1

## SNAP - SNAP County Level and Participation Data
We are interested in the <code>Calc: SNAP Total PA and Non-PA People</code> column.

In [5]:
SNAP = pd.read_excel('./snap-zip-fns388a-7/Jan 2019.xls', header=3)

In [6]:
SNAP.columns

Index(['Substate/Region', 'SNAP All Persons Public Assistance Participation',
       'Unnamed: 2', 'SNAP All Persons Non-Public Assistance Participation',
       'Unnamed: 4', 'Calc: SNAP Total PA and Non-PA People', 'Unnamed: 6',
       'SNAP All Households Public Assistance Participation', 'Unnamed: 8',
       'SNAP All Households Non-Public Assistance Participation',
       'Unnamed: 10', 'Calc: SNAP Total PA and Non-PA Households',
       'Unnamed: 12', 'SNAP All Total Actual PA & Non-PA Issuance'],
      dtype='object')

In [7]:
SNAP = SNAP.drop(columns=['Unnamed: 2', 'Unnamed: 4', 'Unnamed: 6', 'Unnamed: 8', 'Unnamed: 10', 'Unnamed: 12'])
SNAP.head()

,Substate/Region,SNAP All Persons Public Assistance Participation,SNAP All Persons Non-Public Assistance Participation,Calc: SNAP Total PA and Non-PA People,SNAP All Households Public Assistance Participation,SNAP All Households Non-Public Assistance Participation,Calc: SNAP Total PA and Non-PA Households,SNAP All Total Actual PA & Non-PA Issuance
0,0100101 AL EBT AUTAUGA CO FS OFF,958,6501,7459,526,2833,3359,1655504.0
1,0100301 AL EBT BALDWIN CO FS OFF,1897,18484,20381,1117,7736,8853,4579998.0
2,0100501 AL EBT BARBOUR CO FS OFF,832,5116,5948,463,2247,2710,1335147.0
3,0100701 AL EBT BIBB CO FS OFF,503,2666,3169,307,1208,1515,667252.0
4,0100901 AL EBT BLOUNT CO FS OFF,883,4811,5694,563,2083,2646,1177374.0

In [8]:
SNAP_PR = SNAP[['Substate/Region', 'Calc: SNAP Total PA and Non-PA People']].copy()
SNAP_PR.head()

                    Substate/Region Calc: SNAP Total PA and Non-PA People
0  0100101 AL EBT AUTAUGA CO FS OFF                                  7459
1  0100301 AL EBT BALDWIN CO FS OFF                                 20381
2  0100501 AL EBT BARBOUR CO FS OFF                                  5948
3     0100701 AL EBT BIBB CO FS OFF                                  3169
4   0100901 AL EBT BLOUNT CO FS OFF                                  5694

## ACS - American Community Survey
We are interested in these data tables: <code>S1901_C01_012E</code>, <code>S1701_C03_001E</code>, <code>S0101_C01_001E</code>.
- <code>S1901_C01_012E</code>: Median household income (inflation-adjusted, 2010 dollars)
- <code>S1701_C03_001E</code>: Percent of people below poverty level
- <code>S0101_C01_001E</code>: Total population

In [9]:
with open('ACS_key.txt', 'r') as file:
    key = file.read()
key = key.rstrip('\n')

In [10]:
api_url = f'https://api.census.gov/data/2019/acs/acs5/subject?get=NAME,S1901_C01_012E,S1701_C03_001E,S0101_C01_001E&for=county:*&key={key}'
response = requests.get(api_url)

In [11]:
ACS = pd.DataFrame(response.json())
ACS.columns = ACS.iloc[0]
ACS = ACS.drop(0).reset_index(drop=True)
ACS.head()

,NAME,S1901_C01_012E,S1701_C03_001E,S0101_C01_001E,state,county
0,"Lake County, Illinois",89427,7.9,701473,17,097
1,"Fayette County, Illinois",46650,17.2,21565,17,051
2,"Logan County, Illinois",57308,9.3,29003,17,107
3,"Saline County, Illinois",44090,21.1,23994,17,165
4,"Massac County, Illinois",47481,16.7,14219,17,127

## Joining For Final Dataset

First we aggregate the tract level food atlas data to county level and extract fips

In [12]:
FARA_FD['fips'] = FARA_FD['CensusTract'].astype(str).str[:5]

FARA_FD.head()

,CensusTract,State,County,Urban,LILATracts_1And10,HUNVFlag,fips
0,1001020100,Alabama,Autauga County,1,0,0,10010
1,1001020200,Alabama,Autauga County,1,1,0,10010
2,1001020300,Alabama,Autauga County,1,0,0,10010
3,1001020400,Alabama,Autauga County,1,0,0,10010
4,1001020500,Alabama,Autauga County,1,0,1,10010

In [13]:
def mode(x):
    m = x.mode()
    return m.iloc[0] if not m.empty else None

FARA_FD = FARA_FD.groupby(['State', 'County']).agg({
    'Urban': 'mean',
    'LILATracts_1And10': 'mean',
    'HUNVFlag': 'mean',
    'fips': mode
}).reset_index()

FARA_FD

        State             County     Urban  LILATracts_1And10  HUNVFlag   fips
0     Alabama     Autauga County  0.583333           0.416667  0.250000  10010
1     Alabama     Baldwin County  0.451613           0.129032  0.193548  10030
2     Alabama     Barbour County  0.222222           0.444444  0.333333  10059
3     Alabama        Bibb County  0.000000           0.000000  0.500000  10070
4     Alabama      Blount County  0.111111           0.000000  0.444444  10090
...       ...                ...       ...                ...       ...    ...
3137  Wyoming  Sweetwater County  0.500000           0.000000  0.083333  56037
3138  Wyoming       Teton County  0.250000           0.000000  0.000000  56039
3139  Wyoming       Uinta County  0.000000           0.000000  0.333333  56041
3140  Wyoming    Washakie County  0.666667           0.000000  0.000000  56043
3141  Wyoming      Weston County  0.500000           0.000000  0.000000  56045

[3142 rows x 6 columns]

Now we extract fips for <code>SNAP</code>

In [14]:
SNAP_PR['fips'] = SNAP_PR['Substate/Region'].str.extract(r'(^\d{5})')
SNAP_PR = SNAP_PR.rename(columns={'Calc: SNAP Total PA and Non-PA People': 'SNAP_Participants'})
SNAP_PR = SNAP_PR[SNAP_PR['fips'].notna()]

SNAP_PR

                            Substate/Region SNAP_Participants   fips
0          0100101 AL EBT AUTAUGA CO FS OFF              7459  01001
1          0100301 AL EBT BALDWIN CO FS OFF             20381  01003
2          0100501 AL EBT BARBOUR CO FS OFF              5948  01005
3             0100701 AL EBT BIBB CO FS OFF              3169  01007
4           0100901 AL EBT BLOUNT CO FS OFF              5694  01009
...                                     ...               ...    ...
2725  5514901 WI EBT BAD RIVER TRIBAL COUNC               416  55149
2726  5515101 WI EBT LAC DU FLAMBEAU TRIBAL              1068  55151
2727  5515301 WI EBT SOKAOGON TRIBAL AGENCY               170  55153
2728        5515501 WI EBT POTAWATOMI TRIBE                33  55155
2729         5600002 WY EBT WYOMING SD PASS             28009  56000

[2730 rows x 3 columns]

Now extract fips for <code>ACS</code>

In [15]:
ACS['fips'] = ACS['state'] + ACS['county']
ACS.head()

,NAME,S1901_C01_012E,S1701_C03_001E,S0101_C01_001E,state,county,fips
0,"Lake County, Illinois",89427,7.9,701473,17,097,17097
1,"Fayette County, Illinois",46650,17.2,21565,17,051,17051
2,"Logan County, Illinois",57308,9.3,29003,17,107,17107
3,"Saline County, Illinois",44090,21.1,23994,17,165,17165
4,"Massac County, Illinois",47481,16.7,14219,17,127,17127

Now we merge

In [23]:
# --- Food Access (FARA): keep fips + food access + optional labels ---
FARA_small = FARA_FD[['fips', 'State', 'County', 'Urban', 'LILATracts_1And10', 'HUNVFlag']]

# --- SNAP: keep fips + total participants ---
SNAP_small = SNAP_PR[['fips', 'SNAP_Participants']]

# --- ACS: keep fips + income + poverty + population ---
ACS_small = ACS[['fips', 'S1901_C01_012E', 'S1701_C03_001E', 'S0101_C01_001E']].rename(
    columns={
        'S1901_C01_012E': 'MedianIncome',
        'S1701_C03_001E': 'PovertyPercent',
        'S0101_C01_001E': 'TotalPopulation'
    }
)

In [24]:
FARA_small.head()

    fips    State          County     Urban  LILATracts_1And10  HUNVFlag
0  10010  Alabama  Autauga County  0.583333           0.416667  0.250000
1  10030  Alabama  Baldwin County  0.451613           0.129032  0.193548
2  10059  Alabama  Barbour County  0.222222           0.444444  0.333333
3  10070  Alabama     Bibb County  0.000000           0.000000  0.500000
4  10090  Alabama   Blount County  0.111111           0.000000  0.444444

In [25]:
SNAP_small.head()

    fips SNAP_Participants
0  01001              7459
1  01003             20381
2  01005              5948
3  01007              3169
4  01009              5694

In [26]:
ACS_small.head()

0   fips MedianIncome PovertyPercent TotalPopulation
0  17097        89427            7.9          701473
1  17051        46650           17.2           21565
2  17107        57308            9.3           29003
3  17165        44090           21.1           23994
4  17127        47481           16.7           14219

In [30]:
acs_snap = ACS_small.merge(SNAP_small, on='fips', how='inner')
final_df = acs_snap.merge(FARA_small, on='fips', how='inner')
final_df = final_df[[
    'fips',
    'State',
    'County',
    'Urban',
    'LILATracts_1And10',
    'HUNVFlag',
    'SNAP_Participants',
    'MedianIncome',
    'PovertyPercent',
    'TotalPopulation'
]]

final_df.head()

,fips,State,County,Urban,LILATracts_1And10,HUNVFlag,SNAP_Participants,MedianIncome,PovertyPercent,TotalPopulation
0,17097,Illinois,Lake County,0.927632,0.052632,0.105263,62752,89427,7.9,701473
1,17051,Illinois,Fayette County,0.285714,0.714286,0.142857,,46650,17.2,21565
2,17107,Illinois,Logan County,0.375000,0.000000,0.375000,7680,57308,9.3,29003
3,17165,Illinois,Saline County,0.555556,0.333333,0.222222,9434,44090,21.1,23994
4,17127,Illinois,Massac County,0.500000,0.250000,0.250000,3849,47481,16.7,14219

In [31]:
final_df.to_csv('final_food_access_analysis_dataset.csv', index=False)